name: The Deep End
favicon: null
layout_spectrum: 0.75761
typography_spectrum: 0.46068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323232'
    - '#0078aa'
    - '#585858'
    - '#7c7c7c'
  brandStrength: 1
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
